### PR TITLE
remove models and use from demeris-backend-models

### PR DESCRIPTION
**Pull request by akhilkumarpilli**

### CODE REVIEW

**Review by pitasi — CHANGES_REQUESTED** [review]
not sure why your changes to `swagger_gen.go` are not enough but `make generate-swagger` fails now on my machine. Was it working on yours?

if it fails on yours machine too, it's probably sufficient to update swagger comments like this:

```
// @Success 200 {object} BalancesResponse
```

becomes

```
// @Success 200 {object} apimodels.BalancesResponse
```

**Comment by akhilkumarpilli** [comment]
> not sure why your changes to `swagger_gen.go` are not enough but `make generate-swagger` fails now on my machine. Was it working on yours?
> 
> if it fails on yours machine too, it's probably sufficient to update swagger comments like this:
> 
> ```
> // @Success 200 {object} BalancesResponse
> ```
> 
> becomes
> 
> ```
> // @Success 200 {object} apimodels.BalancesResponse
> ```

Sorry, missed that. Thank you.

**Review by pitasi — APPROVED** [review]
thanks for addressing the swagger problem! LGTM :)

**Comment by sahith-narahari** [comment]
I would like to understand why we're doing this. I agree with Antonio's comments in chat, we already have sdk service repos and utils(sometimes) to be updated when making a pr on api-server. This will add one more repo making prs on api server delayed and also lead to confusion if multiple endpoints are being worked on at once

**Comment by akhilkumarpilli** [comment]
> I would like to understand why we're doing this. I agree with Antonio's comments in chat, we already have sdk service repos and utils(sometimes) to be updated when making a pr on api-server. This will add one more repo making prs on api server delayed and also lead to confusion if multiple endpoints are being worked on at once

Getting below errors with tests when trying to add api-server dependency:

```
# sigs.k8s.io/controller-runtime/pkg/log
../../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/log/deleg.go:163:2: cannot use res (type *DelegatingLogger) as type logr.Logger in return argument
../../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/log/deleg.go:179:2: cannot use res (type *DelegatingLogger) as type logr.Logger in return argument
../../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/log/deleg.go:195:2: cannot use res (type *DelegatingLogger) as type logr.Logger in return argument
../../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/log/log.go:67:26: cannot use NullLogger{} (type NullLogger) as type logr.Logger in argument to Log.Fulfill
../../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/log/log.go:82:41: cannot use NullLogger{} (type NullLogger) as type logr.Logger in argument to NewDelegatingLogger
../../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/log/log.go:86:6: cannot use Log (type *DelegatingLogger) as type logr.Logger in assignment
../../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/log/log.go:88:13: assignment mismatch: 1 variable but logr.FromContext returns 2 values
../../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/log/null.go:30:5: cannot use NullLogger{} (type NullLogger) as type logr.Logger in assignment
../../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/log/null.go:48:32: undefined: logr.InfoLogger
../../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/log/null.go:54:2: cannot use log (type NullLogger) as type logr.Logger in return argument
../../../../pkg/mod/sigs.k8s.io/controller-runtime@v0.9.0/pkg/log/null.go:54:2: too many errors
# k8s.io/client-go/applyconfigurations/apiserverinternal/v1alpha1
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/apiserverinternal/v1alpha1/storageversion.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*v1alpha1.StorageVersion, typed.ParseableType, string, *StorageVersionApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
# k8s.io/client-go/applyconfigurations/admissionregistration/v1beta1
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/admissionregistration/v1beta1/mutatingwebhookconfiguration.go:61:34: not enough arguments in call to managedfields.ExtractInto
        have (*v1beta1.MutatingWebhookConfiguration, typed.ParseableType, string, *MutatingWebhookConfigurationApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/admissionregistration/v1beta1/validatingwebhookconfiguration.go:61:34: not enough arguments in call to managedfields.ExtractInto
        have (*v1beta1.ValidatingWebhookConfiguration, typed.ParseableType, string, *ValidatingWebhookConfigurationApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
# k8s.io/client-go/applyconfigurations/admissionregistration/v1
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/admissionregistration/v1/mutatingwebhookconfiguration.go:61:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/admissionregistration/v1".MutatingWebhookConfiguration, typed.ParseableType, string, *MutatingWebhookConfigurationApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/admissionregistration/v1/validatingwebhookconfiguration.go:61:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/admissionregistration/v1".ValidatingWebhookConfiguration, typed.ParseableType, string, *ValidatingWebhookConfigurationApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
# k8s.io/client-go/applyconfigurations/autoscaling/v1
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/autoscaling/v1/horizontalpodautoscaler.go:63:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/autoscaling/v1".HorizontalPodAutoscaler, typed.ParseableType, string, *HorizontalPodAutoscalerApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
# k8s.io/client-go/applyconfigurations/autoscaling/v2beta1
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/autoscaling/v2beta1/horizontalpodautoscaler.go:63:34: not enough arguments in call to managedfields.ExtractInto
        have (*v2beta1.HorizontalPodAutoscaler, typed.ParseableType, string, *HorizontalPodAutoscalerApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
# k8s.io/client-go/applyconfigurations/certificates/v1
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/certificates/v1/certificatesigningrequest.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/certificates/v1".CertificateSigningRequest, typed.ParseableType, string, *CertificateSigningRequestApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
# k8s.io/client-go/applyconfigurations/core/v1
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/core/v1/componentstatus.go:61:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/core/v1".ComponentStatus, typed.ParseableType, string, *ComponentStatusApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/core/v1/configmap.go:64:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/core/v1".ConfigMap, typed.ParseableType, string, *ConfigMapApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/core/v1/endpoints.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/core/v1".Endpoints, typed.ParseableType, string, *EndpointsApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/core/v1/event.go:75:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/core/v1".Event, typed.ParseableType, string, *EventApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/core/v1/limitrange.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/core/v1".LimitRange, typed.ParseableType, string, *LimitRangeApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/core/v1/namespace.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/core/v1".Namespace, typed.ParseableType, string, *NamespaceApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/core/v1/node.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/core/v1".Node, typed.ParseableType, string, *NodeApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/core/v1/persistentvolume.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/core/v1".PersistentVolume, typed.ParseableType, string, *PersistentVolumeApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/core/v1/persistentvolumeclaim.go:63:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/core/v1".PersistentVolumeClaim, typed.ParseableType, string, *PersistentVolumeClaimApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/core/v1/pod.go:63:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/core/v1".Pod, typed.ParseableType, string, *PodApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/core/v1/pod.go:63:34: too many errors
# k8s.io/client-go/applyconfigurations/autoscaling/v2beta2
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/autoscaling/v2beta2/horizontalpodautoscaler.go:63:34: not enough arguments in call to managedfields.ExtractInto
        have (*v2beta2.HorizontalPodAutoscaler, typed.ParseableType, string, *HorizontalPodAutoscalerApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
# k8s.io/client-go/applyconfigurations/certificates/v1beta1
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/certificates/v1beta1/certificatesigningrequest.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*v1beta1.CertificateSigningRequest, typed.ParseableType, string, *CertificateSigningRequestApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
# k8s.io/client-go/applyconfigurations/coordination/v1
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/coordination/v1/lease.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/coordination/v1".Lease, typed.ParseableType, string, *LeaseApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
# k8s.io/client-go/applyconfigurations/flowcontrol/v1alpha1
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/flowcontrol/v1alpha1/flowschema.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*v1alpha1.FlowSchema, typed.ParseableType, string, *FlowSchemaApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/flowcontrol/v1alpha1/prioritylevelconfiguration.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*v1alpha1.PriorityLevelConfiguration, typed.ParseableType, string, *PriorityLevelConfigurationApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
# k8s.io/client-go/applyconfigurations/flowcontrol/v1beta1
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/flowcontrol/v1beta1/flowschema.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*v1beta1.FlowSchema, typed.ParseableType, string, *FlowSchemaApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/flowcontrol/v1beta1/prioritylevelconfiguration.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*v1beta1.PriorityLevelConfiguration, typed.ParseableType, string, *PriorityLevelConfigurationApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
# k8s.io/client-go/applyconfigurations/policy/v1
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/policy/v1/poddisruptionbudget.go:63:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/policy/v1".PodDisruptionBudget, typed.ParseableType, string, *PodDisruptionBudgetApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
# k8s.io/client-go/applyconfigurations/coordination/v1beta1
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/coordination/v1beta1/lease.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*v1beta1.Lease, typed.ParseableType, string, *LeaseApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
# k8s.io/client-go/applyconfigurations/rbac/v1
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/rbac/v1/clusterrole.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/rbac/v1".ClusterRole, typed.ParseableType, string, *ClusterRoleApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/rbac/v1/clusterrolebinding.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/rbac/v1".ClusterRoleBinding, typed.ParseableType, string, *ClusterRoleBindingApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/rbac/v1/role.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/rbac/v1".Role, typed.ParseableType, string, *RoleApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/rbac/v1/rolebinding.go:63:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/rbac/v1".RoleBinding, typed.ParseableType, string, *RoleBindingApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
# k8s.io/client-go/applyconfigurations/rbac/v1alpha1
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/rbac/v1alpha1/clusterrole.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*v1alpha1.ClusterRole, typed.ParseableType, string, *ClusterRoleApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/rbac/v1alpha1/clusterrolebinding.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*v1alpha1.ClusterRoleBinding, typed.ParseableType, string, *ClusterRoleBindingApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/rbac/v1alpha1/role.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*v1alpha1.Role, typed.ParseableType, string, *RoleApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/rbac/v1alpha1/rolebinding.go:63:34: not enough arguments in call to managedfields.ExtractInto
        have (*v1alpha1.RoleBinding, typed.ParseableType, string, *RoleBindingApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
# k8s.io/client-go/applyconfigurations/scheduling/v1
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/scheduling/v1/priorityclass.go:65:34: not enough arguments in call to managedfields.ExtractInto
        have (*"k8s.io/api/scheduling/v1".PriorityClass, typed.ParseableType, string, *PriorityClassApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
# k8s.io/client-go/applyconfigurations/rbac/v1beta1
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/rbac/v1beta1/clusterrole.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*v1beta1.ClusterRole, typed.ParseableType, string, *ClusterRoleApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/rbac/v1beta1/clusterrolebinding.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*v1beta1.ClusterRoleBinding, typed.ParseableType, string, *ClusterRoleBindingApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/rbac/v1beta1/role.go:62:34: not enough arguments in call to managedfields.ExtractInto
        have (*v1beta1.Role, typed.ParseableType, string, *RoleApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/rbac/v1beta1/rolebinding.go:63:34: not enough arguments in call to managedfields.ExtractInto
        have (*v1beta1.RoleBinding, typed.ParseableType, string, *RoleBindingApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
# k8s.io/client-go/applyconfigurations/scheduling/v1alpha1
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/scheduling/v1alpha1/priorityclass.go:65:34: not enough arguments in call to managedfields.ExtractInto
        have (*v1alpha1.PriorityClass, typed.ParseableType, string, *PriorityClassApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string)
# k8s.io/client-go/tools/cache
../../../../pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:180:119: cannot use realClock (type *"k8s.io/apimachinery/pkg/util/clock".RealClock) as type "k8s.io/utils/clock".Clock in argument to wait.NewExponentialBackoffManager:
        *"k8s.io/apimachinery/pkg/util/clock".RealClock does not implement "k8s.io/utils/clock".Clock (wrong type for NewTimer method)
                have NewTimer(time.Duration) "k8s.io/apimachinery/pkg/util/clock".Timer
                want NewTimer(time.Duration) "k8s.io/utils/clock".Timer
../../../../pkg/mod/k8s.io/client-go@v0.21.1/tools/cache/reflector.go:181:119: cannot use realClock (type *"k8s.io/apimachinery/pkg/util/clock".RealClock) as type "k8s.io/utils/clock".Clock in argument to wait.NewExponentialBackoffManager:
        *"k8s.io/apimachinery/pkg/util/clock".RealClock does not implement "k8s.io/utils/clock".Clock (wrong type for NewTimer method)
                have NewTimer(time.Duration) "k8s.io/apimachinery/pkg/util/clock".Timer
                want NewTimer(time.Duration) "k8s.io/utils/clock".Timer
# k8s.io/client-go/applyconfigurations/scheduling/v1beta1
../../../../pkg/mod/k8s.io/client-go@v0.21.1/applyconfigurations/scheduling/v1beta1/priorityclass.go:65:34: not enough arguments in call to managedfields.ExtractInto
        have (*v1beta1.PriorityClass, typed.ParseableType, string, *PriorityClassApplyConfiguration)
        want (runtime.Object, typed.ParseableType, string, interface {}, string
```

**Comment by sahith-narahari** [comment]
How is changing packages resolving this? I would look if we're using a client from different repo or version compatibility. Is there a branch where I can reproduce this?

**Comment by akhilkumarpilli** [comment]
Closing this PR as issue was fixed with https://github.com/allinbits/demeris-backend/pull/501

**Pull request closed without merging**
