### PR TITLE
bugfix(account): return `verified = false` on DenomTrace query fail

### LINKED ISSUE #27: Trace verification still fails
See https://api.emeris.com/v1/account/d214c44aba0331c0f76e53ec80cbddc051fde22f/balance

This was supposed to have been fixed here https://github.com/allinbits/demeris-backend/pull/222, but apparently it's still happening

### PR DESCRIPTION
**Pull request by gsora**
Before this PR a `/balance` query which contained a unverified denomination trace would return error.

Instead, we adopt the same approach we used in `/verify_trace`, and return `verified = false` on such occasions, letting the query still return `200 OK`, along with the original IBC denom.

This PR will be cherry-picked back to `sahith/fix-prodn` for a speedy deployment on production, since `main` here already implements `sdk-service` integration.

Please, double-check everything here because I feel awful today and might've introduced weird bugs :^)

Closes #27.

### CODE REVIEW

**Comment by sgerogia** [comment]
Unit-test to make sure it behaves as expected?

**Comment by gsora** [comment]
Do we have the basis framework in place to write those?

**Comment by gsora** [comment]
@sgerogia please review now with added unit-tests.

**Review by sgerogia — APPROVED** [review]

**Review by DeshErBojhaa — APPROVED** [review]

**Review by sahith-narahari — APPROVED** [review]

**Comment by gamarin2** [comment]
LGTM

**Pull request merged**
