### PR TITLE
fix osmosis apr calculation

### PR DESCRIPTION
**Pull request by 0xbala-k**
https://medium.com/osmosis/osmo-token-distribution-ae27ea2bb4db
image

According to this only 25% of minted tokens are distributed as staking rewards
. So the "apr inflation" would be 25% of the mint inflation
. If we divide the apr we got from [prod](https://api.emeris.com/v1/chain/osmosis/apr) (248.17) with 4 (25%)........we get 62.04 which is exactly the apr shown in keplr

### CODE REVIEW

**Review by akhilkumarpilli — APPROVED** [review]

**Review by PrathyushaLakkireddy — APPROVED** [review]

**Comment by pitasi** [comment]
@SpideyPool192 you were missing the "minor" label 😛 
I'll tag the repo

**Comment by 0xbala-k** [comment]
> @SpideyPool192 you were missing the "minor" label 😛 I'll tag the repo

There are no breaking changes in this pr. Do we still need to add version tags.

**Comment by pitasi** [comment]
Yes so we can track what changes are deployed in the clusters (dev, staging, prod) and it's easy to rollback if something went wrong.

I'll post a message a slack so we are on the same page!

**Comment by 0xbala-k** [comment]
Our slack access isn't back yet.🙂

**Comment by pitasi** [comment]
oh damn sorry, I'll report my message here for now:

Hey folks I saw a bit on confusion around the versioning of api-server (and tracelistener, but most of the changes are being made to api-server) because I didn’t explain it better, sorry! I’m doing it now:

We are now trying to use semver for our deployed services. The goals are:
- increase “readability”: at a glance I can now see that DEV is running api-server 1.7.0, I can rollback to 1.6.0 if something is wrong.
- avoid use of main or latest as docker images tags, this prevents accidentally deployed changes
- if we like this pattern we will adopt it in other services: sdk-service, cns-server, etc

⚠️ If you don’t add a label like minor to your PRs the git tag won’t be generated and the image won’t be deployed.
We can discuss if we prefer to have an implicit “default” and treat no labels as “minor”.

This shouldn’t affect CD in any way, we continue our efforts for rolling out changes in the most automated possible way. We’ll just use v1.2.3 instead of commit hashes.

**Pull request merged**
