### PR TITLE
Feature Staking params

### PR DESCRIPTION
**Pull request by DeshErBojhaa**

### CODE REVIEW

**Review by gsora — APPROVED** [review]
Approving because code looks okay, please solve build issues before merging.

Thanks!

**Review by sgerogia — COMMENTED** [review]
Unit test?

**Comment by DeshErBojhaa** [comment]
> Unit test?

I feel like demeris backend is the more _natural_ place for unit test for this feature.
https://github.com/allinbits/demeris-backend/blob/87a2413207b494575b792cabbd1b84b7484394f5/tests/chains/mint_params_test.go#L16

what do you think?

**Review by lukitsbrian — APPROVED** [review]
LGTM

**Pull request merged**
