### PR TITLE
feat/sentry: use latest sentryx impl

### PR DESCRIPTION
**Pull request by tbruyelle**
Also use latest price-oracle and fix its import path

### CODE REVIEW

**Review by pitasi — APPROVED** [review]
cool, lgtm!

**Comment by tbruyelle** [comment]
One test fails because it expects to read some JSON while the endpoint returned a 500 error. This is no longer possible since I replaced the custom `catchPanics` with the `zap.Recover` for consistency with other services.

I don't think it really matters to return JSON when there's a 500, so I suggest to change the test according to that.

About this specific test in general, it is  useless. The 500 happens because the test try to read the Major version of the `Chain.CosmosSDKVersion`, which is unset, which leads to a panic. If I set the field, the error became a 400 because `sdkservice` is not available. So for this test to became useful, it requires far more work for this tiny PR.

**Comment by pitasi** [comment]
> I don't think it really matters to return JSON when there's a 500 

hmm the json we returned contains a correlation ID that makes it easier for us to retrieve logs for that particular HTTP request though

**Comment by tbruyelle** [comment]
> > I don't think it really matters to return JSON when there's a 500
> 
> hmm the json we returned contains a correlation ID that makes it easier for us to retrieve logs for that particular HTTP request though

Is it acceptable if this ID is in the response headers ? There's already a defined header for that `X-Correlation-Id`, but for some reason it's only propagated to the response if it's present in the request.

https://github.com/EmerisHQ/emeris-utils/blob/9290e0e85b3c53eb6af9e9165d690ea49fc77ade/logging/correlation.go#L21-L62

I can provide a small fix ensuring the response header is always set with this ID.

**Review by DeshErBojhaa — APPROVED** [review]
🎉

**Comment by pitasi** [comment]
> Is it acceptable if this ID is in the response headers ? There's already a defined header for that `X-Correlation-Id`, but for some reason it's only propagated to the response if it's present in the request.
> 
> [EmerisHQ/emeris-utils@`9290e0e`/logging/correlation.go#L21-L62](https://github.com/EmerisHQ/emeris-utils/blob/9290e0e85b3c53eb6af9e9165d690ea49fc77ade/logging/correlation.go#L21-L62)
> 
> I can provide a small fix ensuring the response header is always set with this ID.

we have two "correlation IDs", to be honest I'm not sure why :)

one comes (optionally) as a header in the request and we should just propagate it

the other is called "internal" (int) and is generated by the backend itself

I don't want to block this PR for this, so: yes, let's merge your PR and cleanup our correlation IDs later 😁

**Review by pitasi — APPROVED** [review]

**Comment by tbruyelle** [comment]
> > Is it acceptable if this ID is in the response headers ? There's already a defined header for that `X-Correlation-Id`, but for some reason it's only propagated to the response if it's present in the request.
> > [EmerisHQ/emeris-utils@`9290e0e`/logging/correlation.go#L21-L62](https://github.com/EmerisHQ/emeris-utils/blob/9290e0e85b3c53eb6af9e9165d690ea49fc77ade/logging/correlation.go#L21-L62)
> > I can provide a small fix ensuring the response header is always set with this ID.
> 
> we have two "correlation IDs", to be honest I'm not sure why :)
> 
> one comes (optionally) as a header in the request and we should just propagate it
> 
> the other is called "internal" (int) and is generated by the backend itself
> 
> I don't want to block this PR for this, so: yes, let's merge your PR and cleanup our correlation IDs later grin

Thank you @Pitasi, I created an issue to discuss about that correlationID usage https://github.com/EmerisHQ/demeris-backend/issues/774.

**Pull request merged**
