### PR TITLE
refactor: clean up errors code

### PR DESCRIPTION
**Pull request by pitasi**
I'm trying to clean the code around error creation, error logging, and error responses to the user.

In this PR I have:
- moved the custom Error struct to its own package
- created a separate struct for "user facing errors" (= the json returned in case of errors)
- remove the ID from our Error struct, it will be middlewares' responsability to set up the logger to log that id, and to populate the ID field when returning the error to the user

### CODE REVIEW

**Review by akhilkumarpilli — APPROVED** [review]
LGTM

**Review by DeshErBojhaa — CHANGES_REQUESTED** [review]
We actually don't need a new type for public facing errors. Just a new meth on api err.

```go
type Error struct {
	Namespace     string `json:"ns"`
	StatusCode    int    `json:"-"`
	LowLevelError error  `json:"-"`
	Cause         string `json:"cause"`
    Id            string `json:"id, omitempty"`
}
func (e Error) Public(id string) Error {
	e.Id = id
	return e
}
```

Then on `router/router.go`

```go
c.AbortWithStatusJSON(
	http.StatusInternalServerError,
	err.Public(tryGetIntCorrelationID(c)),
)
```
And
```go
c.JSON(err.StatusCode, err.Public(tryGetIntCorrelationID(c)))
```


What do you think??

**Comment by pitasi** [comment]
> We actually don't need a new type for public facing errors. Just a new meth on api err.
> 
> ```go
> type Error struct {
> 	Namespace     string `json:"ns"`
> 	StatusCode    int    `json:"-"`
> 	LowLevelError error  `json:"-"`
> 	Cause         string `json:"cause"`
>     Id            string `json:"id, omitempty"`
> }
> func (e Error) Public(id string) Error {
> 	e.Id = id
> 	return e
> }
> ```
> 
> Then on `router/router.go`
> 
> ```go
> c.AbortWithStatusJSON(
> 	http.StatusInternalServerError,
> 	err.Public(tryGetIntCorrelationID(c)),
> )
> ```
> 
> And
> 
> ```go
> c.JSON(err.StatusCode, err.Public(tryGetIntCorrelationID(c)))
> ```
> 
> What do you think??

I think it's a bit harder to understand the flow for someone who opens the Error struct and sees an "ID" field but then it realizes that ID is empty until the very end of the response, when the middleware sets it.

I know we have two almost-identical structs but it's a small price to pay for readability imho. Are you concerned about that duplication?

**Comment by pitasi** [comment]
for example we currently have logs like this:

```
{"int_correlation_id": "1c4ac7c0-e5a2-4b14-bbec-2479bafd03f6", "id": "", "name": "akash", "error": "rpc error: code = Unimplemented desc = unknown method StakingPool for service sdk_utilities.SdkUtilities", "error": "1c4ac7c0-e5a2-4b14-bbec-2479bafd03f6 @ chains: cannot retrieve staking pool from sdk-service"}
```

with both int_correlation_id (correctly populated) and id (empty), then inside the error message the id is inside the string again

that's the kind of confusion I'm trying to address 😁

**Comment by DeshErBojhaa** [comment]
> that's the kind of confusion I'm trying to address 😁

`omitempty` takes care of that, doesn't it? Anyway, I don't have strong opinion on duplicated structs. Use your discretion.

**Comment by pitasi** [comment]
I thought about it again (I swear!) but I'd prefer to keep it this way, as I want to separate three principal kind of structs:

1. input data / payload / body of the requests, we *currently* don't have those (I'm 100% sure we will as we'll refactor endpoints and add some basic filters at the very least)
2. domain (in this moment they coincide with the database structs)
3. output data / response body (basically a struct that gets marshalled in json)

**Review by DeshErBojhaa — APPROVED** [review]

**Pull request merged**
